import type {
  NormalizedCase,
  ResultConfidence,
  TestCaseIR,
  TestCaseIRCapability,
  TestCaseIRNode,
  TestCaseIRSourceType,
  TestCaseIRTranslationMetadata,
  TestCaseIRType
} from "../types.js";
import type { DynamicActionPlan, DynamicActionStep } from "./actionPlan.js";

export function buildTestCaseIR(
  testCase: NormalizedCase,
  plan: DynamicActionPlan,
  translation: TestCaseIRTranslationMetadata = ruleTranslationMetadata()
): TestCaseIR {
  const preconditions = plan.steps
    .filter((step) => step.source === "precondition")
    .map((step) => buildPreconditionNode(testCase, step));
  const actions = plan.steps
    .filter((step) => step.source === "test_step")
    .map((step) => buildActionNode(testCase, step));
  const assertions = plan.expectedChecks.flatMap((step) => buildAssertionNodes(testCase, step));

  return {
    version: "test_case_ir.v1",
    case_id: testCase.stable_id,
    title: testCase.title,
    goal: testCase.intent || testCase.title,
    preconditions,
    actions,
    assertions,
    translation,
    notes: [
      "IR v1 is generated from Paragon natural-language test cases before Playwright execution.",
      "Playwright executes generic capabilities mapped from this IR; low-confidence/manual nodes stay conservative."
    ]
  };
}

export function ruleTranslationMetadata(): TestCaseIRTranslationMetadata {
  return {
    provider: "rules",
    status: "rules_only",
    validation_errors: [],
    validation_warnings: [],
    notes: ["Generated by the local rule-based Test Case IR compiler."]
  };
}

function buildPreconditionNode(testCase: NormalizedCase, step: DynamicActionStep): TestCaseIRNode {
  const text = normalize(step.sourceText);
  const isPage = /\b(on|in)\b.+\bpage\b|\bpage\b/.test(text);
  const isExistingData = /\bexists|existing|at least one|has|listed|available|records?\b/.test(text);
  const isAuth = /\blogged in|login|access\b/.test(text);
  const irType: TestCaseIRType = isExistingData
    ? "precondition_existing_data"
    : isPage
      ? "precondition_page"
      : isAuth
        ? "precondition_auth"
        : "precondition_general";

  return node({
    testCase,
    kind: "precondition",
    sourceType: "precondition",
    sourceIndex: step.index,
    sourceText: step.sourceText,
    irType,
    target: step.target,
    confidence: isExistingData ? "medium" : step.confidence,
    capability: isExistingData ? "blocked" : "attemptable",
    reason: isExistingData
      ? "Existing data prerequisite requires seed/API/UI setup before it can be verified reliably."
      : "Precondition was normalized from the uploaded test case.",
    playwrightHint: irType === "precondition_page"
      ? "Use page discovery to reach the inferred module page."
      : undefined
  });
}

function buildActionNode(testCase: NormalizedCase, step: DynamicActionStep): TestCaseIRNode {
  const text = normalize(step.sourceText);
  const target = step.target;

  if (step.action === "navigate") {
    const isBack = normalize(target ?? step.sourceText) === "back" || /\bback\b/.test(text);
    return node({
      testCase,
      kind: "action",
      sourceType: "test_step",
      sourceIndex: step.index,
      sourceText: step.sourceText,
      irType: isBack ? "navigate_back" : "navigate_to_page",
      target: isBack ? "back" : target,
      confidence: "medium",
      capability: "executable",
      reason: isBack
        ? "Step explicitly asks to return to the previous page."
        : "Step explicitly asks to navigate to a page or menu area.",
      playwrightHint: isBack ? "page.goBack()" : "Use page discovery/menu route hints."
    });
  }

  if (step.action === "click") {
    const dialogAction = dialogActionLabel(target ?? step.sourceText);
    const rowAction = rowActionLabel(`${target ?? ""} ${step.sourceText}`);
    const tableLink = isTableIdentityLink(target, step.sourceText);
    const irType: TestCaseIRType = tableLink
      ? "click_table_link"
      : rowAction
        ? "click_row_action"
        : dialogAction
          ? "click_dialog_action"
          : "click_target";

    return node({
      testCase,
      kind: "action",
      sourceType: "test_step",
      sourceIndex: step.index,
      sourceText: step.sourceText,
      irType,
      target: tableLink ? target ?? "row link" : rowAction ?? dialogAction ?? target,
      row: rowContext(step.sourceText),
      scope: dialogAction ? "visible_dialog_or_drawer" : tableLink || rowAction ? "visible_table" : undefined,
      confidence: irType === "click_target" ? step.confidence : "medium",
      capability: irType === "click_target" ? "attemptable" : "executable",
      reason: clickReason(irType),
      playwrightHint: clickHint(irType)
    });
  }

  if (step.action === "fill") {
    return node({
      testCase,
      kind: "action",
      sourceType: "test_step",
      sourceIndex: step.index,
      sourceText: step.sourceText,
      irType: "fill_field",
      target,
      value: step.value,
      scope: /modal|dialog|drawer/.test(text) ? "visible_dialog_or_drawer" : undefined,
      confidence: step.value ? "medium" : "low",
      capability: step.value || target ? "attemptable" : "manual",
      reason: step.value
        ? "Step contains an explicit fill value."
        : "Step asks for a field change, but a safe generated value may be needed.",
      playwrightHint: "Resolve a visible form field, then fill an explicit or generated safe test value."
    });
  }

  if (step.action === "select") {
    return node({
      testCase,
      kind: "action",
      sourceType: "test_step",
      sourceIndex: step.index,
      sourceText: step.sourceText,
      irType: "select_option",
      target,
      value: step.value,
      scope: /filter/.test(text) ? "filter_or_dialog" : undefined,
      confidence: step.value ? "medium" : "low",
      capability: step.value && target ? "attemptable" : "manual",
      reason: "Step asks for selecting an option from a dropdown/select control.",
      playwrightHint: "Resolve select-like control, open popper, choose matching option value."
    });
  }

  if (step.action === "wait") {
    return node({
      testCase,
      kind: "action",
      sourceType: "test_step",
      sourceIndex: step.index,
      sourceText: step.sourceText,
      irType: "wait_for_update",
      confidence: "medium",
      capability: "executable",
      reason: "Step asks to wait for page or table update.",
      playwrightHint: "Wait for observable page state/table data to settle."
    });
  }

  const changeField = inferChangeFieldTarget(step.sourceText);
  if (changeField) {
    return node({
      testCase,
      kind: "action",
      sourceType: "test_step",
      sourceIndex: step.index,
      sourceText: step.sourceText,
      irType: "fill_field",
      target: changeField.target,
      value: "safe_generated_value",
      scope: /modal|dialog|drawer/.test(text) ? "visible_dialog_or_drawer" : undefined,
      confidence: changeField.target ? "medium" : "low",
      capability: changeField.target ? "attemptable" : "manual",
      reason: changeField.target
        ? "Step asks to change an editable field and gives an example target."
        : "Step asks to change a field but does not identify which field.",
      playwrightHint: "Resolve the named field when available, then fill a safe generated test value."
    });
  }

  return node({
    testCase,
    kind: "action",
    sourceType: "test_step",
    sourceIndex: step.index,
    sourceText: step.sourceText,
    irType: "observe_only",
    target,
    confidence: "low",
    capability: "manual",
    reason: "Step does not map to a deterministic browser action yet.",
    playwrightHint: "Record page observation and leave the step for manual review."
  });
}

function buildAssertionNodes(testCase: NormalizedCase, step: DynamicActionStep): TestCaseIRNode[] {
  const text = normalize(step.sourceText);
  const irTypes = inferAssertionTypes(text);

  return irTypes.map((irType, index) => {
    const confidence = assertionConfidence(irType);
    const capability = assertionCapability(irType);

    return node({
      testCase,
      kind: "assertion",
      sourceType: "expected_result",
      sourceIndex: step.index,
      sourceText: step.sourceText,
      irType,
      target: step.target,
      confidence,
      capability,
      reason: assertionReason(irType),
      playwrightHint: assertionHint(irType),
      idSuffix: irTypes.length > 1 ? `assertion_${index + 1}` : undefined
    });
  });
}

function node(input: {
  testCase: NormalizedCase;
  kind: TestCaseIRNode["kind"];
  sourceType: TestCaseIRSourceType;
  sourceIndex: number;
  sourceText: string;
  irType: TestCaseIRType;
  target?: string;
  value?: string;
  scope?: string;
  row?: string;
  confidence: ResultConfidence;
  capability: TestCaseIRCapability;
  reason: string;
  playwrightHint?: string;
  idSuffix?: string;
}): TestCaseIRNode {
  return {
    id: `${input.testCase.stable_id}.${input.sourceType}.${input.sourceIndex}${input.idSuffix ? `.${input.idSuffix}` : ""}`,
    kind: input.kind,
    source_type: input.sourceType,
    source_index: input.sourceIndex,
    source_text: input.sourceText,
    ir_type: input.irType,
    target: input.target,
    value: input.value,
    scope: input.scope,
    row: input.row,
    confidence: input.confidence,
    capability: input.capability,
    reason: input.reason,
    playwright_hint: input.playwrightHint
  };
}

function inferAssertionTypes(text: string): TestCaseIRType[] {
  const types: TestCaseIRType[] = [];
  if (/download|exported file|downloaded file|generated file|error log/.test(text)) {
    types.push("assert_download_content");
  }
  if (/success message|toast|notification|shown|error message|warning message/.test(text)) {
    types.push(/success/.test(text) ? "assert_toast_visible" : "assert_form_validation");
  }
  if (/modal|dialog/.test(text)) {
    types.push(/close|closes|closed|disappear/.test(text) ? "assert_modal_closed" : "assert_modal_visible");
  }
  if (/redirect|detail page|loads successfully|page is displayed|correct page/.test(text)) {
    types.push("assert_navigation");
  }
  if (/table.*filter|only.*display|matching records|match all selected filters/.test(text)) {
    types.push("assert_table_filtered");
  }
  if (/row updates|row reverts|updated data|new data|unchanged data/.test(text)) {
    types.push("assert_table_row_updated");
  }
  if (/column|header|field.*display|all fields|sections are visible/.test(text)) {
    types.push("assert_visible_text");
  }
  if (/null|undefined|empty values|blank/.test(text)) {
    types.push("assert_no_raw_null");
  }

  return Array.from(new Set(types.length > 0 ? types : ["assert_manual_review"]));
}

function assertionConfidence(type: TestCaseIRType): ResultConfidence {
  if (type === "assert_manual_review" || type === "assert_download_content") return "low";
  if (type === "assert_table_filtered" || type === "assert_no_raw_null" || type === "assert_visible_text") return "medium";
  return "medium";
}

function assertionCapability(type: TestCaseIRType): TestCaseIRCapability {
  if (type === "assert_manual_review" || type === "assert_download_content") return "manual";
  return "attemptable";
}

function assertionReason(type: TestCaseIRType): string {
  switch (type) {
    case "assert_download_content":
      return "Expected result requires download capture and file-content inspection.";
    case "assert_navigation":
      return "Expected result describes reaching a page or route.";
    case "assert_modal_visible":
    case "assert_modal_closed":
      return "Expected result describes modal visibility state.";
    case "assert_toast_visible":
      return "Expected result describes a feedback toast or success message.";
    case "assert_table_filtered":
      return "Expected result describes table rows matching selected filters.";
    case "assert_table_row_updated":
      return "Expected result describes changed or unchanged row data.";
    case "assert_visible_text":
      return "Expected result describes visible fields, sections, or labels.";
    case "assert_no_raw_null":
      return "Expected result describes null/empty value rendering.";
    case "assert_form_validation":
      return "Expected result describes validation or error feedback.";
    default:
      return "Expected result does not map to a reliable generic assertion yet.";
  }
}

function assertionHint(type: TestCaseIRType): string {
  switch (type) {
    case "assert_navigation":
      return "Compare URL, breadcrumb, page title, and visible module labels.";
    case "assert_modal_visible":
      return "Expect visible dialog/drawer with requested controls.";
    case "assert_modal_closed":
      return "Expect previously visible dialog/drawer to be hidden.";
    case "assert_toast_visible":
    case "assert_form_validation":
      return "Inspect toast/message/validation containers for expected feedback.";
    case "assert_table_filtered":
      return "Inspect sampled table rows against applied filter values.";
    case "assert_table_row_updated":
      return "Capture before/after row values and compare changed fields.";
    case "assert_visible_text":
      return "Assert visible text/section labels in the current page scope.";
    case "assert_no_raw_null":
      return "Inspect sampled table/detail fields for raw null-like values.";
    case "assert_download_content":
      return "Capture browser download, parse file, then inspect rows/content.";
    default:
      return "Leave this assertion for manual review until a generic checker exists.";
  }
}

function rowActionLabel(value: string): string | undefined {
  const text = normalize(value);
  if (/\b(edit|modify)\b/.test(text)) return "Edit";
  if (/\b(view|details?|detail)\b/.test(text)) return "Detail";
  if (/\bdelete|remove\b/.test(text)) return "Delete";
  if (/\bapprove\b/.test(text)) return "Approve";
  if (/\breject\b/.test(text)) return "Reject";
  if (/\bcopy|duplicate\b/.test(text)) return "Copy";
  return undefined;
}

function dialogActionLabel(value: string): string | undefined {
  const text = normalize(value);
  if (/\bsave\b/.test(text)) return "Save";
  if (/\bcancel\b/.test(text)) return "Cancel";
  if (/\bsubmit\b/.test(text)) return "Submit";
  if (/\bconfirm\b|\bok\b/.test(text)) return "Confirm";
  return undefined;
}

function isTableIdentityLink(target: string | undefined, sourceText: string): boolean {
  const text = normalize(`${target ?? ""} ${sourceText}`);
  return /\b(user\s*name|username|creator\s*name|name)\b/.test(text) && /\b(row|hyperlink|linked|link)\b/.test(text);
}

function inferChangeFieldTarget(sourceText: string): { target?: string } | undefined {
  const text = normalize(sourceText);
  if (!/\b(change|edit|modify|update)\b/.test(text) || !/\bfield|value|data\b/.test(text)) {
    return undefined;
  }

  const example = sourceText.match(/e\.g\.,?\s*([^)]+)\)/i)?.[1]?.trim();
  const quoted = sourceText.match(/"([^"]+)"/)?.[1]?.trim();
  return { target: quoted || example };
}

function rowContext(sourceText: string): string | undefined {
  const text = normalize(sourceText);
  if (/\bsame row\b/.test(text)) return "same_row";
  if (/\bdifferent row\b/.test(text)) return "different_row";
  if (/\bspecific row\b|\ba row\b|\bfor a specific\b/.test(text)) return "first_visible_or_contextual_row";
  return undefined;
}

function clickReason(type: TestCaseIRType): string {
  switch (type) {
    case "click_table_link":
      return "Step asks to click a link-like value inside a table row.";
    case "click_row_action":
      return "Step asks to click an action in a table row operation column.";
    case "click_dialog_action":
      return "Step asks to click a known action inside a visible dialog/drawer.";
    default:
      return "Step asks to click a visible UI target.";
  }
}

function clickHint(type: TestCaseIRType): string {
  switch (type) {
    case "click_table_link":
      return "Resolve first/same-row link-like element in Element UI or standard table body.";
    case "click_row_action":
      return "Resolve row-scoped operation button by row context and action label.";
    case "click_dialog_action":
      return "Resolve exact button text inside the active dialog/drawer/popup.";
    default:
      return "Use scope-aware target resolver on current page observation.";
  }
}

function normalize(value: string): string {
  return value
    .replace(/[“”]/g, "\"")
    .replace(/[‘’]/g, "'")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}
